export const categories = [
  {
    id: 0,
    name: 'web development',
    problems: 10,
    solutions: 20,
    contributers: 10,
  },
  {
    id: 1,
    name: 'mobile app development',
    problems: 8,
    solutions: 15,
    contributors: 12,
  },
  {
    id: 2,
    name: 'data science',
    problems: 12,
    solutions: 25,
    contributors: 18,
  },
  {
    id: 3,
    name: 'artificial intelligence',
    problems: 15,
    solutions: 30,
    contributors: 22,
  },
  {
    id: 4,
    name: 'machine learning',
    problems: 9,
    solutions: 18,
    contributors: 11,
  },
  {
    id: 5,
    name: 'cloud computing',
    problems: 7,
    solutions: 14,
    contributors: 9,
  },
  {
    id: 6,
    name: 'cybersecurity',
    problems: 11,
    solutions: 22,
    contributors: 15,
  },
  {
    id: 7,
    name: 'UI/UX design',
    problems: 6,
    solutions: 12,
    contributors: 8,
  },
  {
    id: 8,
    name: 'game development',
    problems: 14,
    solutions: 28,
    contributors: 20,
  },
  {
    id: 9,
    name: 'networking',
    problems: 5,
    solutions: 10,
    contributors: 7,
  },
  {
    id: 10,
    name: 'e-commerce',
    problems: 13,
    solutions: 26,
    contributors: 17,
  },
  {
    id: 11,
    name: 'blockchain',
    problems: 8,
    solutions: 16,
    contributors: 11,
  },
  {
    id: 12,
    name: 'robotics',
    problems: 9,
    solutions: 19,
    contributors: 13,
  },
  {
    id: 13,
    name: 'digital marketing',
    problems: 10,
    solutions: 21,
    contributors: 16,
  },
  {
    id: 14,
    name: 'augmented reality',
    problems: 7,
    solutions: 13,
    contributors: 10,
  },
  {
    id: 15,
    name: 'virtual reality',
    problems: 6,
    solutions: 11,
    contributors: 9,
  },
  {
    id: 16,
    name: 'big data',
    problems: 12,
    solutions: 24,
    contributors: 19,
  },
  {
    id: 17,
    name: 'internet of things',
    problems: 10,
    solutions: 20,
    contributors: 14,
  },
  {
    id: 18,
    name: 'computer vision',
    problems: 9,
    solutions: 17,
    contributors: 12,
  },
  {
    id: 19,
    name: 'natural language processing',
    problems: 11,
    solutions: 23,
    contributors: 15,
  },
]
