import { Knex } from "knex";
import crypto from "crypto";

exports.seed = async function (knex: Knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: crypto.randomUUID(),
      firstName: "Muhammad",
      lastName: "Banhawy",
      username: "benho",
      password: "@qwerty123",
      email: "user1@example.com",
      role: "admin",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Jane",
      lastName: "Doe",
      username: "user2",
      password: "password2",
      email: "user2@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Alice",
      lastName: "Smith",
      username: "user3",
      password: "password3",
      email: "user3@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Bob",
      lastName: "Johnson",
      username: "user4",
      password: "password4",
      email: "user4@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Emily",
      lastName: "Brown",
      username: "user5",
      password: "password5",
      email: "user5@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "David",
      lastName: "Wilson",
      username: "user6",
      password: "password6",
      email: "user6@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Emma",
      lastName: "Taylor",
      username: "user7",
      password: "password7",
      email: "user7@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "James",
      lastName: "Martinez",
      username: "user8",
      password: "password8",
      email: "user8@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Olivia",
      lastName: "Hernandez",
      username: "user9",
      password: "password9",
      email: "user9@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "William",
      lastName: "Young",
      username: "user10",
      password: "password10",
      email: "user10@example.com",
      role: "user",
      deletedAt: new Date(),
    },
    {
      id: crypto.randomUUID(),
      firstName: "Sophia",
      lastName: "Lee",
      username: "user11",
      password: "password11",
      email: "user11@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Michael",
      lastName: "King",
      username: "user12",
      password: "password12",
      email: "user12@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Isabella",
      lastName: "Lopez",
      username: "user13",
      password: "password13",
      email: "user13@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Daniel",
      lastName: "Gonzalez",
      username: "user14",
      password: "password14",
      email: "user14@example.com",
      role: "user",
    },
    {
      id: crypto.randomUUID(),
      firstName: "Mia",
      lastName: "Moore",
      username: "user15",
      password: "password15",
      email: "user15@example.com",
      role: "user",
      // add deletedAt to test soft delete
      deletedAt: new Date(),
    },
  ]);
};
