import { Container } from 'inversify';
import { AuthController } from '../rest/controllers/auth.controller';
import { UserController } from '../rest/controllers/user.controller';
import ApplicationRouter from '../rest/routes';
import { AuthService, IAuthService } from '../rest/services';
import { IJwtService } from '../rest/services/jwt/jwt.service';
import { JwtService } from '../rest/services/jwt/jwt.service.impl';
import { IUserService } from '../rest/services/user/user.service';
import { UserService } from '../rest/services/user/user.service.imp';
import { symbols } from './symbols';
import { DataSource, Repository } from 'typeorm';
import { IUserRepository } from '../../contracts/repositories/user.repository';
import { UserRepository } from '../rest/repositories/user.repo';
import { UserDomain } from '../../domain/entities/user.domain';
const container = new Container();

container.bind(ApplicationRouter).to(ApplicationRouter);
container.bind<IUserService>(symbols.IUserService).to(UserService);
container.bind<IUserRepository>(symbols.IUserRepository).to(UserRepository).inSingletonScope();
container.bind<IJwtService>(symbols.IJwtService).to(JwtService);
container.bind<IAuthService>(symbols.IAuthService).to(AuthService);
container.bind<UserController>(symbols.IUserController).to(UserController);
container.bind<AuthController>(symbols.IAuthController).to(AuthController);
container.bind<DataSource>(symbols.DataSource).to(DataSource);
export { container };
